# rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: agic-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: agic-cluster-role
subjects:
- kind: ServiceAccount
  name: agic-service-account
  namespace: <your_namespace>
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: agic-cluster-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]

