apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress-ingress
  annotations:
{{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: "{{ $value }}"
{{- end }}
spec:
  rules:
    - http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: wordpress-service
                port:
                  number: {{ .Values.service.port }}
